E0s: average
batch_size: 4
checkpoints_dir: NN4/11/
default_dtype: float32
device: cuda
ema: true
ema_decay: 0.99
enable_cueq: false
energy_key: REF_energy
energy_weight: 1.0
forces_key: REF_forces
forces_weight: 2.0
log_dir: NN4/11/
loss: weighted
max_L: 1
max_num_epochs: 30
model: MACE
model_dir: NN4/11/
name: '11'
num_channels: 100
optimizer: schedulefree
plot: false
r_max: 5.5
results_dir: NN4/11/
seed: 123
swa: false
train_file: NN4/11/train.xyz
valid_file: NN4/11/valid.xyz
